-- PropTXChange Seed Data
-- Run AFTER schema.sql
-- Replace the bcrypt hashes with real ones generated by:
--   php -r "echo password_hash('YourPassword', PASSWORD_BCRYPT);"

USE rpm_db;

-- Sample admin (password: Admin@1234 — replace hash!)
INSERT IGNORE INTO user_profiles (id, role, full_name, email, password_hash)
VALUES (
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'admin', 'Property Manager',
  'admin@proptxchange.com',
  '$2y$12$REPLACE_WITH_REAL_BCRYPT_HASH_HERE_admin'
);

-- Sample neighborhood
INSERT IGNORE INTO neighborhoods (id, name, city, state_code)
VALUES ('11111111-1111-1111-1111-111111111111', 'Crown Heights', 'Brooklyn', 'NY');

-- Sample property
INSERT IGNORE INTO properties (id, admin_id, neighborhood_id, name, address, city, state_code, zip_code)
VALUES (
  '22222222-2222-2222-2222-222222222222',
  'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
  '11111111-1111-1111-1111-111111111111',
  '412 Nostrand', '412 Nostrand Ave', 'Brooklyn', 'NY', '11216'
);

-- Sample units
INSERT IGNORE INTO units (id, property_id, unit_number, bedrooms, bathrooms, monthly_rent, is_occupied)
VALUES
  ('33333333-0000-0000-0000-000000000001', '22222222-2222-2222-2222-222222222222', '2B', 2, 1.0, 1850.00, 1),
  ('33333333-0000-0000-0000-000000000002', '22222222-2222-2222-2222-222222222222', '3A', 2, 1.0, 2100.00, 1);

-- To add a tenant:
-- 1. Register via the website (creates user_profiles + tenants rows)
-- 2. Admin assigns the unit by updating: UPDATE tenants SET unit_id='...' WHERE id='...';
